# Generated by Django 3.2.7 on 2021-09-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='your_name',
            new_name='user',
        ),
    ]
