# Generated by Django 3.2.9 on 2021-11-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210904_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
