# Generated by Django 3.2.9 on 2021-11-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('shopename', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=70)),
            ],
        ),
    ]
