# Generated by Django 3.2.9 on 2021-11-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_sellerregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddress',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
